require "user.plugins"
require "user.base"
require "themes.dracula-theme"
-- require "themes.pywal-theme"

require "user.cmp"
require "user.lsp"
require "user.renamer"
require "user.alpha"
require "user.autopairs"
require "user.nvim-tree"
require "user.indentline"
require "user.bufferline"
require "user.statusline"
require "user.treesitter"
require "user.telescope"
require "user.comment"
require "user.toggleterm"
require "user.colorizer"

require "user.keymaps"
