# https://wiki.archlinux.org/index.php/GTK#Configuration
[Settings]
gtk-icon-theme-name=oomox-xresources-reverse
gtk-theme-name=oomox-xresources-reverse
gtk-font-name="SF UI Display 12"
gtk-titlebar-double-click="none"
gtk-titlebar-right-click="none"
gtk-application-prefer-dark-theme=0
gtk-decoration-layout=""
gtk-enable-primary-paste=false
