[env]
TERM = "xterm-256color"

[font]
size = 15.5

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "None"
dynamic_padding = true
# gtk_theme_variant = "none"
opacity = 0.7

[window.padding]
x = 0
y = 0
