#!/bin/bash

FILE=$HOME/Pictures/Wallpapers/$1

if [ -f "$FILE" ]; then
    wpg -a $FILE
    wpg -s $1
    wal -q -i $FILE
    rm $HOME/.Xresources
    cp $HOME/.cache/wal/.Xresources $HOME
    xrdb -merge ~/.Xresources
    rm $HOME/.dotfiles/.scripts/lock
    cp $HOME/.cache/wal/lock-alpha.sh $HOME/.dotfiles/.scripts/lock
    chmod +x $HOME/.dotfiles/.scripts/lock 
    spicetify update
    pywal-discord
    feh --bg-fill $FILE
    echo 'awesome.restart()' | awesome-client &> /dev/null

else 
    echo "$1 does not exist. The image must be in the $HOME/Pictures/Wallpapers directory. Check and try again."
fi

